import Link from "next/link";
import MealSearch from "./components/searchMeals/MealSearch";
import Image from "next/image";

export const metadata = {
  title: "All meals ",
  description: "Generated by create next app",
};

const mealPage = async ({ searchParams }) => {
  const query = await searchParams;

  //*    HANDLE FETCH =========>
  const fetchMeals = async () => {
    try {
      const res = await fetch(
        `https://www.themealdb.com/api/json/v1/1/search.php?s=${query.search}`
      );
      const data = await res.json();
      // setMealData(data?.meals || []);
      return data.meals;
    } catch (error) {
      console.log(error);
    }
  };

  const mealData = await fetchMeals();

  return (
    <>
      <div>
        <MealSearch />
      </div>

      <div className="grid grid-cols-4 w-11/12 mx-auto">
        {mealData?.map((meal) => (
          <div key={meal.strMeal} className="border m-4 bg-[#84a98c] p-4 rounded">
            <div className="flex justify-center items-center">
              <Image
                className=" "
                height={680}
                width={680}
                src={`${meal.strMealThumb}`}
                alt=""
              />
            </div>
            <p className="text-2xl text-center"> {meal?.strMeal} </p>
            <div className="flex justify-center items-center mb-2">
              <Link href={`/meals/${meal.idMeal}`}>
                <button className="bg-green-600 px-2 py-1 rounded cursor-pointer">
                  Details
                </button>
              </Link>
            </div>
          </div>
        ))}
      </div>
    </>
  );
};

export default mealPage;
